/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/renderer/index.html', './src/renderer/src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    colors: {
      transparent: 'transparent',
      current:     'currentColor',
      white:       '#ffffff',
      black:       '#000000',

      bg:  'var(--bg)',
      s0:  'var(--s0)',
      s1:  'var(--s1)',
      s2:  'var(--s2)',
      s3:  'var(--s3)',
      s4:  'var(--s4)',

      b0:  'var(--b0)',
      b1:  'var(--b1)',
      b2:  'var(--b2)',

      t0:  'var(--t0)',
      t1:  'var(--t1)',
      t2:  'var(--t2)',

      a0:  'var(--a0)',
      a1:  'var(--a1)',

      ok:  'var(--ok)',
      er:  'var(--er)',
      wa:  'var(--wa)',
      inn: 'var(--in)',

      /* semantic aliases for legacy classes */
      accent:  'var(--a0)',
      green:   'var(--ok-t)',
      red:     'var(--er-t)',
      danger:  'var(--er)',
      warning: 'var(--wa)',
      surface: 'var(--s0)',
      border:  'var(--b0)',
      'text-1':'var(--t0)',
      'text-2':'var(--t1)',
      'text-3':'var(--t2)',
    },
    borderColor: ({ theme }) => ({ ...theme('colors'), DEFAULT: 'var(--b0)' }),
    borderRadius: {
      none: '0',
      xs:   'var(--r2)',
      sm:   'var(--r4)',
      md:   'var(--r6)',
      lg:   'var(--r8)',
      xl:   'var(--r10)',
      '2xl':'var(--r12)',
      full: '9999px',
    },
    fontFamily: { sans: 'var(--font)', mono: 'var(--font-mono)' },
    fontSize: {
      '2xs': ['10px', '14px'],
      xs:    ['11px', '15px'],
      sm:    ['12px', '16px'],
      md:    ['13px', '18px'],
      base:  ['14px', '20px'],
      lg:    ['16px', '22px'],
      xl:    ['18px', '26px'],
      '2xl': ['22px', '30px'],
      '3xl': ['28px', '36px'],
      '4xl': ['36px', '44px'],
      '5xl': ['48px', '56px'],
    },
    fontWeight: {
      normal:   '400',
      medium:   '500',
      semibold: '600',
      bold:     '700',
      black:    '800',
    },
    boxShadow: {
      none: 'none',
      1:    'var(--sh1)',
      2:    'var(--sh2)',
      3:    'var(--sh3)',
      4:    'var(--sh4)',
      5:    'var(--sh5)',
    },
    extend: {
      width:    { sidebar: 'var(--sidebar-w)' },
      minWidth: { sidebar: 'var(--sidebar-w)' },
      spacing: { 13: '52px', 15: '60px', 18: '72px' },
    },
  },
  plugins: [],
}
